[package]
name = "lib_export_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
file_ref={ git="https://github.com/SuccessfullyFailed/file_ref.git" }
omni_parser={ git="https://github.com/SuccessfullyFailed/omni_parser.git" }
regex = "1.11.1"