[package]
name = "crate_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
file_ref={ git="https://github.com/SuccessfullyFailed/file_ref.git" }
glyph_kit={ git="https://github.com/SuccessfullyFailed/glyph_kit.git" }
cachew={ git="https://github.com/SuccessfullyFailed/cachew.git" }